// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/roasted_octocat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelPromptType int32

const (
	ModelPromptType_ModelPromptType_EARLY2000s   ModelPromptType = 0
	ModelPromptType_ModelPromptType_UWUIFIED     ModelPromptType = 1
	ModelPromptType_ModelPromptType_NERD         ModelPromptType = 2
	ModelPromptType_ModelPromptType_OLDENGLISH   ModelPromptType = 3
	ModelPromptType_ModelPromptType_NICE         ModelPromptType = 4
	ModelPromptType_ModelPromptType_REGINAGEORGE ModelPromptType = 5
	ModelPromptType_ModelPromptType_DISCORDMOD   ModelPromptType = 6
	ModelPromptType_ModelPromptType_DCVILLIAN    ModelPromptType = 7
)

// Enum value maps for ModelPromptType.
var (
	ModelPromptType_name = map[int32]string{
		0: "ModelPromptType_EARLY2000s",
		1: "ModelPromptType_UWUIFIED",
		2: "ModelPromptType_NERD",
		3: "ModelPromptType_OLDENGLISH",
		4: "ModelPromptType_NICE",
		5: "ModelPromptType_REGINAGEORGE",
		6: "ModelPromptType_DISCORDMOD",
		7: "ModelPromptType_DCVILLIAN",
	}
	ModelPromptType_value = map[string]int32{
		"ModelPromptType_EARLY2000s":   0,
		"ModelPromptType_UWUIFIED":     1,
		"ModelPromptType_NERD":         2,
		"ModelPromptType_OLDENGLISH":   3,
		"ModelPromptType_NICE":         4,
		"ModelPromptType_REGINAGEORGE": 5,
		"ModelPromptType_DISCORDMOD":   6,
		"ModelPromptType_DCVILLIAN":    7,
	}
)

func (x ModelPromptType) Enum() *ModelPromptType {
	p := new(ModelPromptType)
	*p = x
	return p
}

func (x ModelPromptType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelPromptType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_roasted_octocat_proto_enumTypes[0].Descriptor()
}

func (ModelPromptType) Type() protoreflect.EnumType {
	return &file_proto_roasted_octocat_proto_enumTypes[0]
}

func (x ModelPromptType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelPromptType.Descriptor instead.
func (ModelPromptType) EnumDescriptor() ([]byte, []int) {
	return file_proto_roasted_octocat_proto_rawDescGZIP(), []int{0}
}

type GetParsedGithubResultRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GithubToken      string                 `protobuf:"bytes,1,opt,name=githubToken,proto3" json:"githubToken,omitempty"`
	IdempotencyToken string                 `protobuf:"bytes,2,opt,name=idempotencyToken,proto3" json:"idempotencyToken,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetParsedGithubResultRequest) Reset() {
	*x = GetParsedGithubResultRequest{}
	mi := &file_proto_roasted_octocat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParsedGithubResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParsedGithubResultRequest) ProtoMessage() {}

func (x *GetParsedGithubResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roasted_octocat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParsedGithubResultRequest.ProtoReflect.Descriptor instead.
func (*GetParsedGithubResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_roasted_octocat_proto_rawDescGZIP(), []int{0}
}

func (x *GetParsedGithubResultRequest) GetGithubToken() string {
	if x != nil {
		return x.GithubToken
	}
	return ""
}

func (x *GetParsedGithubResultRequest) GetIdempotencyToken() string {
	if x != nil {
		return x.IdempotencyToken
	}
	return ""
}

type GetParsedGithubResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Result        *string                `protobuf:"bytes,2,opt,name=result,proto3,oneof" json:"result,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParsedGithubResultResponse) Reset() {
	*x = GetParsedGithubResultResponse{}
	mi := &file_proto_roasted_octocat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParsedGithubResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParsedGithubResultResponse) ProtoMessage() {}

func (x *GetParsedGithubResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roasted_octocat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParsedGithubResultResponse.ProtoReflect.Descriptor instead.
func (*GetParsedGithubResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_roasted_octocat_proto_rawDescGZIP(), []int{1}
}

func (x *GetParsedGithubResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetParsedGithubResultResponse) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

func (x *GetParsedGithubResultResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ParseGithubRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GithubToken      string                 `protobuf:"bytes,1,opt,name=githubToken,proto3" json:"githubToken,omitempty"`
	IdempotencyToken string                 `protobuf:"bytes,2,opt,name=idempotencyToken,proto3" json:"idempotencyToken,omitempty"`
	PromptType       ModelPromptType        `protobuf:"varint,3,opt,name=promptType,proto3,enum=roastedoctocat.ModelPromptType" json:"promptType,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ParseGithubRequest) Reset() {
	*x = ParseGithubRequest{}
	mi := &file_proto_roasted_octocat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseGithubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseGithubRequest) ProtoMessage() {}

func (x *ParseGithubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roasted_octocat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseGithubRequest.ProtoReflect.Descriptor instead.
func (*ParseGithubRequest) Descriptor() ([]byte, []int) {
	return file_proto_roasted_octocat_proto_rawDescGZIP(), []int{2}
}

func (x *ParseGithubRequest) GetGithubToken() string {
	if x != nil {
		return x.GithubToken
	}
	return ""
}

func (x *ParseGithubRequest) GetIdempotencyToken() string {
	if x != nil {
		return x.IdempotencyToken
	}
	return ""
}

func (x *ParseGithubRequest) GetPromptType() ModelPromptType {
	if x != nil {
		return x.PromptType
	}
	return ModelPromptType_ModelPromptType_EARLY2000s
}

type ParseGithubResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyToken string                 `protobuf:"bytes,1,opt,name=idempotencyToken,proto3" json:"idempotencyToken,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ParseGithubResponse) Reset() {
	*x = ParseGithubResponse{}
	mi := &file_proto_roasted_octocat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseGithubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseGithubResponse) ProtoMessage() {}

func (x *ParseGithubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roasted_octocat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseGithubResponse.ProtoReflect.Descriptor instead.
func (*ParseGithubResponse) Descriptor() ([]byte, []int) {
	return file_proto_roasted_octocat_proto_rawDescGZIP(), []int{3}
}

func (x *ParseGithubResponse) GetIdempotencyToken() string {
	if x != nil {
		return x.IdempotencyToken
	}
	return ""
}

type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GithubToken   string                 `protobuf:"bytes,1,opt,name=githubToken,proto3" json:"githubToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_proto_roasted_octocat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roasted_octocat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_proto_roasted_octocat_proto_rawDescGZIP(), []int{4}
}

func (x *WhoAmIRequest) GetGithubToken() string {
	if x != nil {
		return x.GithubToken
	}
	return ""
}

type WhoAmIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_proto_roasted_octocat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roasted_octocat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_proto_roasted_octocat_proto_rawDescGZIP(), []int{5}
}

func (x *WhoAmIResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WhoAmIResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_proto_roasted_octocat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roasted_octocat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_proto_roasted_octocat_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type OAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,3,opt,name=redirectUri,proto3" json:"redirectUri,omitempty"`
	CodeChallenge string                 `protobuf:"bytes,4,opt,name=codeChallenge,proto3" json:"codeChallenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthRequest) Reset() {
	*x = OAuthRequest{}
	mi := &file_proto_roasted_octocat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthRequest) ProtoMessage() {}

func (x *OAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roasted_octocat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthRequest.ProtoReflect.Descriptor instead.
func (*OAuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_roasted_octocat_proto_rawDescGZIP(), []int{7}
}

func (x *OAuthRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuthRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OAuthRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *OAuthRequest) GetCodeChallenge() string {
	if x != nil {
		return x.CodeChallenge
	}
	return ""
}

type OAuthResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccessToken        string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	AccessTokenExpiry  int32                  `protobuf:"varint,2,opt,name=accessTokenExpiry,proto3" json:"accessTokenExpiry,omitempty"`
	RefreshToken       string                 `protobuf:"bytes,3,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	RefreshTokenExpiry int32                  `protobuf:"varint,4,opt,name=refreshTokenExpiry,proto3" json:"refreshTokenExpiry,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OAuthResponse) Reset() {
	*x = OAuthResponse{}
	mi := &file_proto_roasted_octocat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthResponse) ProtoMessage() {}

func (x *OAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roasted_octocat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthResponse.ProtoReflect.Descriptor instead.
func (*OAuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_roasted_octocat_proto_rawDescGZIP(), []int{8}
}

func (x *OAuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuthResponse) GetAccessTokenExpiry() int32 {
	if x != nil {
		return x.AccessTokenExpiry
	}
	return 0
}

func (x *OAuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuthResponse) GetRefreshTokenExpiry() int32 {
	if x != nil {
		return x.RefreshTokenExpiry
	}
	return 0
}

type PingRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyToken string                 `protobuf:"bytes,1,opt,name=idempotencyToken,proto3" json:"idempotencyToken,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_roasted_octocat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roasted_octocat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_roasted_octocat_proto_rawDescGZIP(), []int{9}
}

func (x *PingRequest) GetIdempotencyToken() string {
	if x != nil {
		return x.IdempotencyToken
	}
	return ""
}

type PingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Message          string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ServerVersion    string                 `protobuf:"bytes,2,opt,name=serverVersion,proto3" json:"serverVersion,omitempty"`
	IdempotencyToken string                 `protobuf:"bytes,3,opt,name=idempotencyToken,proto3" json:"idempotencyToken,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_roasted_octocat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roasted_octocat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_roasted_octocat_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *PingResponse) GetIdempotencyToken() string {
	if x != nil {
		return x.IdempotencyToken
	}
	return ""
}

var File_proto_roasted_octocat_proto protoreflect.FileDescriptor

const file_proto_roasted_octocat_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/roasted_octocat.proto\x12\x0eroastedoctocat\"l\n" +
	"\x1cGetParsedGithubResultRequest\x12 \n" +
	"\vgithubToken\x18\x01 \x01(\tR\vgithubToken\x12*\n" +
	"\x10idempotencyToken\x18\x02 \x01(\tR\x10idempotencyToken\"\x84\x01\n" +
	"\x1dGetParsedGithubResultResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\x06result\x18\x02 \x01(\tH\x00R\x06result\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x01R\x05error\x88\x01\x01B\t\n" +
	"\a_resultB\b\n" +
	"\x06_error\"\xa3\x01\n" +
	"\x12ParseGithubRequest\x12 \n" +
	"\vgithubToken\x18\x01 \x01(\tR\vgithubToken\x12*\n" +
	"\x10idempotencyToken\x18\x02 \x01(\tR\x10idempotencyToken\x12?\n" +
	"\n" +
	"promptType\x18\x03 \x01(\x0e2\x1f.roastedoctocat.ModelPromptTypeR\n" +
	"promptType\"A\n" +
	"\x13ParseGithubResponse\x12*\n" +
	"\x10idempotencyToken\x18\x01 \x01(\tR\x10idempotencyToken\"1\n" +
	"\rWhoAmIRequest\x12 \n" +
	"\vgithubToken\x18\x01 \x01(\tR\vgithubToken\">\n" +
	"\x0eWhoAmIResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\"P\n" +
	"\x0eRefreshRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\"\x86\x01\n" +
	"\fOAuthRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12 \n" +
	"\vredirectUri\x18\x03 \x01(\tR\vredirectUri\x12$\n" +
	"\rcodeChallenge\x18\x04 \x01(\tR\rcodeChallenge\"\xb3\x01\n" +
	"\rOAuthResponse\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12,\n" +
	"\x11accessTokenExpiry\x18\x02 \x01(\x05R\x11accessTokenExpiry\x12\"\n" +
	"\frefreshToken\x18\x03 \x01(\tR\frefreshToken\x12.\n" +
	"\x12refreshTokenExpiry\x18\x04 \x01(\x05R\x12refreshTokenExpiry\"9\n" +
	"\vPingRequest\x12*\n" +
	"\x10idempotencyToken\x18\x01 \x01(\tR\x10idempotencyToken\"z\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12$\n" +
	"\rserverVersion\x18\x02 \x01(\tR\rserverVersion\x12*\n" +
	"\x10idempotencyToken\x18\x03 \x01(\tR\x10idempotencyToken*\x84\x02\n" +
	"\x0fModelPromptType\x12\x1e\n" +
	"\x1aModelPromptType_EARLY2000s\x10\x00\x12\x1c\n" +
	"\x18ModelPromptType_UWUIFIED\x10\x01\x12\x18\n" +
	"\x14ModelPromptType_NERD\x10\x02\x12\x1e\n" +
	"\x1aModelPromptType_OLDENGLISH\x10\x03\x12\x18\n" +
	"\x14ModelPromptType_NICE\x10\x04\x12 \n" +
	"\x1cModelPromptType_REGINAGEORGE\x10\x05\x12\x1e\n" +
	"\x1aModelPromptType_DISCORDMOD\x10\x06\x12\x1d\n" +
	"\x19ModelPromptType_DCVILLIAN\x10\a2\xfa\x03\n" +
	"\x0eOctoRoasterAPI\x12A\n" +
	"\x04Ping\x12\x1b.roastedoctocat.PingRequest\x1a\x1c.roastedoctocat.PingResponse\x12D\n" +
	"\x05OAuth\x12\x1c.roastedoctocat.OAuthRequest\x1a\x1d.roastedoctocat.OAuthResponse\x12H\n" +
	"\aRefresh\x12\x1e.roastedoctocat.RefreshRequest\x1a\x1d.roastedoctocat.OAuthResponse\x12G\n" +
	"\x06WhoAmI\x12\x1d.roastedoctocat.WhoAmIRequest\x1a\x1e.roastedoctocat.WhoAmIResponse\x12V\n" +
	"\vParseGithub\x12\".roastedoctocat.ParseGithubRequest\x1a#.roastedoctocat.ParseGithubResponse\x12t\n" +
	"\x15GetParsedGithubResult\x12,.roastedoctocat.GetParsedGithubResultRequest\x1a-.roastedoctocat.GetParsedGithubResultResponseB\x1fZ\x1d./techytechster.com/pkg/protob\x06proto3"

var (
	file_proto_roasted_octocat_proto_rawDescOnce sync.Once
	file_proto_roasted_octocat_proto_rawDescData []byte
)

func file_proto_roasted_octocat_proto_rawDescGZIP() []byte {
	file_proto_roasted_octocat_proto_rawDescOnce.Do(func() {
		file_proto_roasted_octocat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_roasted_octocat_proto_rawDesc), len(file_proto_roasted_octocat_proto_rawDesc)))
	})
	return file_proto_roasted_octocat_proto_rawDescData
}

var file_proto_roasted_octocat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_roasted_octocat_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_roasted_octocat_proto_goTypes = []any{
	(ModelPromptType)(0),                  // 0: roastedoctocat.ModelPromptType
	(*GetParsedGithubResultRequest)(nil),  // 1: roastedoctocat.GetParsedGithubResultRequest
	(*GetParsedGithubResultResponse)(nil), // 2: roastedoctocat.GetParsedGithubResultResponse
	(*ParseGithubRequest)(nil),            // 3: roastedoctocat.ParseGithubRequest
	(*ParseGithubResponse)(nil),           // 4: roastedoctocat.ParseGithubResponse
	(*WhoAmIRequest)(nil),                 // 5: roastedoctocat.WhoAmIRequest
	(*WhoAmIResponse)(nil),                // 6: roastedoctocat.WhoAmIResponse
	(*RefreshRequest)(nil),                // 7: roastedoctocat.RefreshRequest
	(*OAuthRequest)(nil),                  // 8: roastedoctocat.OAuthRequest
	(*OAuthResponse)(nil),                 // 9: roastedoctocat.OAuthResponse
	(*PingRequest)(nil),                   // 10: roastedoctocat.PingRequest
	(*PingResponse)(nil),                  // 11: roastedoctocat.PingResponse
}
var file_proto_roasted_octocat_proto_depIdxs = []int32{
	0,  // 0: roastedoctocat.ParseGithubRequest.promptType:type_name -> roastedoctocat.ModelPromptType
	10, // 1: roastedoctocat.OctoRoasterAPI.Ping:input_type -> roastedoctocat.PingRequest
	8,  // 2: roastedoctocat.OctoRoasterAPI.OAuth:input_type -> roastedoctocat.OAuthRequest
	7,  // 3: roastedoctocat.OctoRoasterAPI.Refresh:input_type -> roastedoctocat.RefreshRequest
	5,  // 4: roastedoctocat.OctoRoasterAPI.WhoAmI:input_type -> roastedoctocat.WhoAmIRequest
	3,  // 5: roastedoctocat.OctoRoasterAPI.ParseGithub:input_type -> roastedoctocat.ParseGithubRequest
	1,  // 6: roastedoctocat.OctoRoasterAPI.GetParsedGithubResult:input_type -> roastedoctocat.GetParsedGithubResultRequest
	11, // 7: roastedoctocat.OctoRoasterAPI.Ping:output_type -> roastedoctocat.PingResponse
	9,  // 8: roastedoctocat.OctoRoasterAPI.OAuth:output_type -> roastedoctocat.OAuthResponse
	9,  // 9: roastedoctocat.OctoRoasterAPI.Refresh:output_type -> roastedoctocat.OAuthResponse
	6,  // 10: roastedoctocat.OctoRoasterAPI.WhoAmI:output_type -> roastedoctocat.WhoAmIResponse
	4,  // 11: roastedoctocat.OctoRoasterAPI.ParseGithub:output_type -> roastedoctocat.ParseGithubResponse
	2,  // 12: roastedoctocat.OctoRoasterAPI.GetParsedGithubResult:output_type -> roastedoctocat.GetParsedGithubResultResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_roasted_octocat_proto_init() }
func file_proto_roasted_octocat_proto_init() {
	if File_proto_roasted_octocat_proto != nil {
		return
	}
	file_proto_roasted_octocat_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_roasted_octocat_proto_rawDesc), len(file_proto_roasted_octocat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_roasted_octocat_proto_goTypes,
		DependencyIndexes: file_proto_roasted_octocat_proto_depIdxs,
		EnumInfos:         file_proto_roasted_octocat_proto_enumTypes,
		MessageInfos:      file_proto_roasted_octocat_proto_msgTypes,
	}.Build()
	File_proto_roasted_octocat_proto = out.File
	file_proto_roasted_octocat_proto_goTypes = nil
	file_proto_roasted_octocat_proto_depIdxs = nil
}
